FROM fedora:26
MAINTAINER Luiz Carvalho <lucarval@redhat.com>

ARG UPDATES
ARG UPDATES_TESTING

RUN touch /var/lib/rpm/*
RUN if [ $UPDATES_TESTING ]; then \
            dnf install -y dnf-plugins-core && \
            dnf config-manager --set-enable updates-testing; fi && \
    if [ $UPDATES ] || [ $UPDATES_TESTING ]; then dnf update -y; fi
